---
title: "2. Lerneinheit: Funktion und Aufbau von Bibliothekssystemen"
date: 2021-10-08
---

<h1>Technische Probleme und viel freie Studienzeit</h1>

<p>Diese Lerneinheit stand im Zeichen der Bibliothekssoftware Koha. Als Hausaufgabe sollten wir das Tutorial 1 dazu ausführen. Dies hatte ich bereits in der letzten Lerneinheit erledigt. Als ich mich nun zum Unterrichtsstart auf Koha einloggen wollte, kam die Meldung das der Server nicht erreichbar sei. Im Unterricht wurde erklärt, dass das ein bekannter Fehler ist, welcher gelöst werden kann, indem der Befehl «sudo systemctl restart koha-common» im Terminal eingegeben wird. Und siehe da, nach dem Neustart hatte Koha wieder funktioniert. Da andere aus der Klasse grössere Probleme hatten, standen ihnen Sessions mit den Dozenten zur Verfügung. Die Pause, die dadurch für mich entstand, nutze ich, um die Koha-Tutorials 2 und 3 durchzuarbeiten. Im <a href="https://zefanjas.de/koha-installation-schule-bibliografische-framework/">Tutorial 2</a> waren weiterführende Links zu MARC21 angegeben, welche ich hilfreich fand. Im 2. Semester haben wir MARC21 kurz angeschaut, ich konnte damals aber nicht ganz folgen, da ich noch keinerlei Vorkenntnisse hatte. Dass ich damals nicht eigenständig weiter recherchierte, rächt sich nun. Somit nutzte ich die Zeit, um mir mehr Wissen zu MARC21 anzueignen. Dabei war das Kapitel «What is a MARC Record, and Why is it Important?” von der Library of Congress <a href="https://www.loc.gov/marc/umb/">Understanding MARC</a> sehr hilfreich. <br> </p>

<p>Als ich mich durch die Tutorials und die MARC21 Informationen durchgearbeitet habe, waren stand noch weitere eigene Lernzeit zur Verfügung. Im Unterrichtsdokument war erwähnt, dass wir bis zur Lerneinheit 4 ArchivesSpace 3.1.0 installieren sollen, was ich somit gleich erledigt habe. Die Installation war einfach. Nur war ich erst etwas irritiert, dass nach dem Befehl ArchivesSpace starten im Terminal so viel Code durchlief und das nicht stoppte. Als ich anschliessend die Notiz im Skript las, war mir dann auch klar warum – das Tool ist nur so lange verfügbar, wie der Prozess im Terminal läuft. Es ist also normal, dass hier der Prozess nicht stoppte. Ich konnte die Administrationsoberfläche von ArchivesSpace öffnen und mich mit den zur Verfügung gestellten Credentials einloggen. Also alles gut und Aufgabe erledigt. <br> </p>

<p>Dann ging es mit dem Unterricht gemeinsam weiter und wir lernten die Oberfläche von Koha kennen. Ein Buch erfassen, es ausleihen und zurückbringen sowie neue Nutzende anlegen waren spannende Tasks. Ich war erstaunt, wie einfach das ging. Die Masken haben zwar teilweise mehr Informationen, als man eigentlich braucht, aber dennoch war die Bedienung relativ effizient. Besonders spannend fand ich die Anbindung der GVK-Datenbank. Mit wenigen Schritten öffnet sich Tür und Tor zu vielen bibliographischen Daten, welche mit wenigen Klicks in den eigenen Katalog importiert werden können. Das Tempo für die Demonstration war angenehm, ich konnte die Schritte simultan mitmachen. Das nächste Thema – der Marktüberblick über Bibliothekssysteme – kam im Unterricht zu kurz. Unter Zeitdruck wurde das Thema angeschnitten. Als Laien, haben mir viele Firmen- und Systemnamen nichts gesagt und somit konnte ich das Ganze nicht richtig einordnen. Aber ich denke, das Wichtigste ist, dass ich weiss, dass eine jährliche Statistik namens «Library Systems Report» von Marshall Breeding im American Libraries Magazine erscheint. Der Report und der Bericht dazu kann über folgenden Link abgerufen werden: <a href="https://americanlibrariesmagazine.org/2021/05/03/2021-library-systems-report/">2021 Library Systems Report</a>. Falls ich beruflich mit Bibliothekssystemen in Berührung kommen sollte, weiss ich, wo ich Informationen zu den aktuell verwendeten Systemen finde. Auch die Problematik von Fusionen oder Aufkäufe in der Branche wurde im Unterricht angesprochen. Das ist sicherlich ein Thema, dass bei einer Evaluation berücksichtigt werden muss. Diese Gedanken im Hinterkopf zu haben, ist sicherlich in keiner Branche verkehrt. Somit kann ich doch etwas mitnehmen aus dieser Lerneinheit. <br> </p>
